workspace:
  base: /go
  path: src/github.com/rendom/drone-irc

pipeline:
  build:
    image: golang:1.8
    commands:
      - go vet
      - GOARCH=amd64 GOOS=linux CGO_ENABLED=0 go build -a -ldflags '-w' -o drone-irc
  publish:
    image: plugins/docker
    repo: rendom/drone-irc
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push
  irc:
    image: rendom/drone-irc
    secrets: [irc_server, irc_nick, irc_tls, irc_channel]
